QuantumEncryption/Pages/Connect.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion.Internal;
using QuantumEncryption.Helper;

namespace QuantumEncryption.Pages
{
    public class ConnectModel : PageModel
    {
        public void OnGet()
        {

        }
        public JsonResult OnGetMatrix()
        {
            //return new JsonResult(getMatrix(45,315));
            // return new JsonResult(getRandomMatrix());
            return new JsonResult(MatrixMultiply());
        }

        static double getAngle(double degrees)
        {
            double angle = Math.PI * degrees / 180.0;
            return angle;
        }
        static double[,] getMatrix(double sinDegre, double cosDegree)
        {
            int rnd = 4;
            double[,] myArray = new double[4, 4];
            myArray[0, 0] = 1; myArray[0, 1] = 0; myArray[0, 2] = Math.Round(Math.Cos(getAngle(cosDegree)), rnd); myArray[0, 3] = Math.Round(Math.Sin(getAngle(sinDegre)), rnd);
            myArray[1, 0] = 0; myArray[1, 1] = 1; myArray[1, 2] = Math.Round(Math.Sin(getAngle(sinDegre)), rnd); myArray[1, 3] = Math.Round(Math.Cos(getAngle(cosDegree)), rnd);
            myArray[2, 0] = Math.Round(Math.Cos(getAngle(cosDegree)), rnd); myArray[2, 1] = Math.Round(Math.Sin(getAngle(sinDegre)), rnd); myArray[2, 2] = Math.Round(Math.Exp(sinDegre), 1); myArray[2, 3] = 0;
            myArray[3, 0] = Math.Round(Math.Sin(getAngle(sinDegre)), rnd); myArray[3, 1] = Math.Round(Math.Cos(getAngle(cosDegree)), rnd); myArray[3, 2] = 0; myArray[3, 3] = Math.Exp(-sinDegre);

            return myArray;
        }
        static double[,] getRandomMatrix()
        {
            Int64 rnd = 100;
            double[,] myArray = new double[4, 4];
            myArray[0, 0] = RSA.GetPrimeNumber(rnd); rnd = rnd - 5;
            myArray[0, 1] = RSA.GetPrimeNumber(rnd); rnd = rnd - 5;
            myArray[0, 2] = RSA.GetPrimeNumber(rnd); rnd = rnd - 5;
            myArray[0, 3] = RSA.GetPrimeNumber(rnd); rnd = rnd - 5;

            myArray[1, 0] = RSA.GetPrimeNumber(rnd); rnd = rnd - 5;
            myArray[1, 1] = RSA.GetPrimeNumber(rnd); rnd = rnd - 5;
            myArray[1, 2] = RSA.GetPrimeNumber(rnd); rnd = rnd - 5;
            myArray[1, 3] = RSA.GetPrimeNumber(rnd); rnd = rnd - 5;

            myArray[2, 0] = RSA.GetPrimeNumber(rnd); rnd = rnd - 5;
            myArray[2, 1] = RSA.GetPrimeNumber(rnd); rnd = rnd - 5;
            myArray[2, 2] = RSA.GetPrimeNumber(rnd); rnd = rnd - 5;
            myArray[2, 3] = RSA.GetPrimeNumber(rnd); rnd = rnd - 5;

            myArray[3, 0] = RSA.GetPrimeNumber(rnd); rnd = rnd - 5;
            myArray[3, 1] = RSA.GetPrimeNumber(rnd); rnd = rnd - 5;
            myArray[3, 2] = RSA.GetPrimeNumber(rnd); rnd = rnd - 5;
            myArray[3, 3] = RSA.GetPrimeNumber(rnd); rnd = rnd - 5;

            return myArray;
        }

        static double[,] MatrixMultiply()
        {
            var a = getMatrix(45,315);
            var b = getRandomMatrix();
            int m = 4, n = 4, p = 4, q = 4, i, j;
            double[,] c = new double[m, q];
            for (i = 0; i < m; i++)
            {
                for (j = 0; j < q; j++)
                {
                    c[i, j] = 0;
                    for (int k = 0; k < n; k++)
                    {
                        c[i, j] += a[i, k] * b[k, j];
                    }
                }
            }
            return c;
        }
    }
}

QuantumEncryption/Pages/DataRequest.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace QuantumEncryption.Pages
{
    public class DataRequestModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

QuantumEncryption/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace QuantumEncryption.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

QuantumEncryption/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using QuantumEncryption.Helper;

namespace QuantumEncryption.Pages
{
    public class IndexModel : PageModel
    {
      
        public SessionModel SessionModel { get; set; }
        public void OnGet()
        {
            SessionModel = Session.GetSessionModel(HttpContext.Session);
        }
    }
}

QuantumEncryption/Pages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using QuantumEncryption.Contexts;
using QuantumEncryption.Helper;
using QuantumEncryption.Models;
using QuantumEncryption.Services;

namespace QuantumEncryption.Pages
{
    [BindProperties]
    public class LoginModel : PageModel
    {
        private readonly ISessionService _service;
        public LoginModel(ISessionService context)
        {
            _service = context;
        }
        public string UserName { get; set; }
        public string UserId { get; set; }
        public string UserKey { get; set; }
        
        public SessionModel SessionModel { get; set; }

        public void OnGet(int Id = 0)
        {
            SessionModel = _service.GetCurrentUser(Id);
            _service.LogoutCurrentUser(Id);
        }
        public ActionResult OnPost()
        {
            var user = new LoggedInUser
            {
                 UserId=UserId,
                 UserKey=UserKey,
                 UserName=UserName,
                 SessionId = HttpContext.Session.Id
            };
            var result = _service.LoggedInUser(user);
            return RedirectToPage("RSAKey",new { id = result.LoggedInUserId });
        }
        public ActionResult OnGetLogout(int Id)
        {
            _service.LogoutCurrentUser(Id);
            return RedirectToPage("Login");
        }

    }

}

QuantumEncryption/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace QuantumEncryption.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

QuantumEncryption/Pages/RSAKey.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using QuantumEncryption.Helper;
using QuantumEncryption.Services;

namespace QuantumEncryption.Pages
{
    public class RSAKeyModel : PageModel
    {
        private readonly ISessionService _service;
        public RSAKeyModel(ISessionService context)
        {
            _service = context;
        }
        public SessionModel SessionModel { get; set; }
        public void OnGet(int Id)
        {
            SessionModel = _service.GetCurrentUser(Id);
        }
    }
}

QuantumEncryption/Pages/Receive.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using QuantumEncryption.Contexts;
using QuantumEncryption.Helper;
using QuantumEncryption.Models;
using QuantumEncryption.Services;

namespace QuantumEncryption.Pages
{
    public class ReceiveModel : PageModel
    {
        private readonly ISessionService _service;
        private readonly AppDbContext _appDbContext;
        public ReceiveModel(ISessionService context, AppDbContext appDbContext)
        {
            _service = context;
            _appDbContext = appDbContext;
        }
        public List<LoggedInUser> LoggedInUsers { get; set; }
        public List<UserData> UserDatas { get; set; }
        public SessionModel SessionModel { get; set; }
        [BindProperty]
        public IFormFile File { get; set; }

        public ActionResult OnGet(int Id)
        {
            setSessionData(Id);
           
            if (string.IsNullOrEmpty(SessionModel.UserKey) || string.IsNullOrEmpty(SessionModel.UserName))
            {
                return RedirectToPage("Login");
            }
           
            return Page();
        }

        public async Task<ActionResult> OnPostDecryptAsync(int Id)
        {
            setSessionData(Id);
            var filePath = Path.GetTempFileName();
            //var result ="";
            string fileContents;
            using (var stream = System.IO.File.Create(filePath))
            {
                await File.CopyToAsync(stream);
            }
            using (StreamReader reader = new StreamReader(filePath))
            {
                fileContents = reader.ReadToEnd();
            }
            var user = await _appDbContext.LoggedInUsers.FindAsync(Id);
          
            Stopwatch stopwatch = Stopwatch.StartNew(); //creates and start the instance of Stopwatch
            var decrypt = RSA.StartDecryption(fileContents, user.UserPrivateKey);
            stopwatch.Stop();
            ViewData["result"] = decrypt;
            ViewData["DecryptionTime"] = stopwatch.ElapsedMilliseconds.ToString();
            return Page();
            // return File(Encoding.UTF8.GetBytes(decrypt), "text/plain", "DecryptedText.txt");
        }
        public ActionResult OnGetDownload(int Id)
        {
            
            var data = _appDbContext.UserDatas.Find(Id);
            return File(Encoding.UTF8.GetBytes(data.EncryptedData), "text/plain", "EcryptedText.txt");
        }
        private void setSessionData(int Id)
        {
            SessionModel = _service.GetCurrentUser(Id);
            UserDatas = _appDbContext.UserDatas.Where(x => x.ReceiverName == SessionModel.UserName).ToList();
        }
    }
}

QuantumEncryption/Pages/Register.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace QuantumEncryption.Pages
{
    public class RegisterModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

QuantumEncryption/Pages/Send.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using QuantumEncryption.Contexts;
using QuantumEncryption.Helper;
using QuantumEncryption.Models;
using QuantumEncryption.Services;

namespace QuantumEncryption.Pages
{
    public class SendModel : PageModel
    {
        private readonly ISessionService _service;
        private readonly AppDbContext _appDbContext;
        public SendModel(ISessionService context, AppDbContext appDbContext)
        {
            _service = context;
            _appDbContext = appDbContext;
        }
        public List<LoggedInUser> LoggedInUsers { get; set; }
        public List<UserData> UserDatas { get; set; }
        public SessionModel SessionModel { get; set; }
        public ActionResult OnGet(int Id)
        {
            setSessionData(Id);
            if (string.IsNullOrEmpty(SessionModel.UserKey) || string.IsNullOrEmpty(SessionModel.UserName))
            {
                return RedirectToPage("Login");
            }
            
            return Page();
        }
        [BindProperty]
        public string Text { get; set; }
        [BindProperty]
        public string Result { get; set; }
        [BindProperty]
        public IFormFile File { get; set; }
        [BindProperty]
        public string ReceiverName { get; set; }
        [BindProperty]
        public string ReceiverKey { get; set; }
        [BindProperty]
        public string SenderName { get; set; }
        public async Task<ActionResult> OnPostEncryptAsync(int Id)
        {
            #region ReadFileContent
            setSessionData(Id);
            var filePath = Path.GetTempFileName();
            //var result ="";
            string fileContents;
            using (var stream = System.IO.File.Create(filePath))
            {
                await File.CopyToAsync(stream);
            }
            using (StreamReader reader = new StreamReader(filePath))
            {
                fileContents = reader.ReadToEnd();
            }
            #endregion

            Stopwatch stopwatch = Stopwatch.StartNew(); //creates and start the instance of Stopwatch
            var encryptesData = RSA.StartEncryption(fileContents, ReceiverKey);
            stopwatch.Stop();
            // Encryotion
           

            #region Sending data to Receiver
            var userdata = new UserData
            {
                SenderName = SenderName,
                ReceiverName = ReceiverName,
                SenderPublicKey = $"{RSA.d},{RSA.n}",
                EncryptedData = encryptesData,
                SendingDatetime=DateTime.Now
            };
            _appDbContext.UserDatas.Add(userdata);
            _appDbContext.SaveChanges();
            #endregion
            ViewData["result"] = encryptesData;
            ViewData["EncryptionTime"] = stopwatch.ElapsedMilliseconds.ToString();

            return Page();

            //return File(Encoding.UTF8.GetBytes(encryptesData), "text/plain", "EncryptedText.txt");
        }
        
        public JsonResult OnGetConnect(int Id)
        {
            return new JsonResult(_service.RequestPublicKey(Id));
        }


        private void setSessionData(int Id)
        {
            SessionModel = _service.GetCurrentUser(Id);
            SenderName = SessionModel.UserName;
            UserDatas = _appDbContext.UserDatas.Where(x => x.SenderName == SessionModel.UserName).ToList();
            LoggedInUsers = _service.GetLoggedInUsers(Id);
        }
    }
}

QuantumEncryption/Pages/Connect.cshtml
@page
@model QuantumEncryption.Pages.ConnectModel
@{
    ViewData["Title"] = "Connect";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Connect</h1>

QuantumEncryption/Pages/DataRequest.cshtml
@page
@model QuantumEncryption.Pages.DataRequestModel
@{
    ViewData["Title"] = "DataRequest";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-6">
        <div class="col-md-12">
            <div class="col-md-8">
                <div class="form-group">
                    <label for="exampleFormControlSelect1">User</label>
                    <select class="form-control" id="Key" name="KeyLength" onchange="keyChange()" required>
                        <option value="">select User</option>
                        <option>3</option>
                        <option>4</option>
                        <option>5</option>
                        <option>6</option>
                        <option>7</option>
                        <option>8</option>
                        <option>9</option>
                        <option>10</option>
                        <option>11</option>
                    </select>
                </div>
            </div>
            <div class="col-md-4">
                <button type="button" id="btn-connect" class="btn btn-primary">Connect</button>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <label for="exampleInputEmail1">Name</label>
                <input type="text" class="form-control" name="Name" aria-describedby="emailHelp" placeholder="Enter Name" required>
            </div>
        </div>
          
            <div class="form-group">
                <label for="exampleInputPassword1">CNIC</label>
                <input type="text" class="form-control" name="CNIC" placeholder="CNIC" required>
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" class="form-control" name="Password" placeholder="Password" required>
            </div>

            <button type="submit" id="btn-login" class="btn btn-primary">Login</button>
        </div>




    </div>

@section Scripts{
    <script>
        var s = 22;
        var r = 1;
        var t = 2;
        var i = 0;
        var length = 0;
        var result = new Array();

        function getBits(s, r, t, i) {
            if (i > length) {
                getFinalBit();
                return;
            }
            // ajax call here
            $.ajax({
                contentType: "application/json",
                url: 'https://quantumapi2.azurewebsites.net/api/Connect/' + s + '/' + r + '/' + t + '/' + i,
                type: 'get'
            }).done(function (response) { //
                RequestBit(response);
            }).fail(function (xhr, status, error) {
                //Ajax request failed.
                var errorMessage = xhr.status + ': ' + xhr.statusText
                //alert('Error - ' + errorMessage);

            })

        }

        function getConnectUser() {

            getBits(s, r, t, i);
        }

        function RequestBit(response) {
            if (i == 0) {
                var length = t * 10;
                var count = response.bit;
                if (count > length) {
                    length = count;
                }
                i = i + 1;
            } else {
                result.push(response);
                i = i + 1;
                getBits(s, r, t, i)
            }
        }

        function getFinalBit() {
            for (var i = 0; i < length; i++) {
                console.log(result[t * i]);
            }
        }

    </script>

}

QuantumEncryption/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
    <partial name="_header" model="Model.SessionModel" />
    <div class="container">
        <main role="main" class="pb-3">
            <div class="text-center">
                <h1 class="display-4">Welcome</h1>
                <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
            </div>
            </main>
</div>

QuantumEncryption/Pages/Receive.cshtml
@page "{id:int}"
@model QuantumEncryption.Pages.ReceiveModel
@{
    ViewData["Title"] = "Receive";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
<partial name="_header" model="Model.SessionModel" />
<div class="container">

    <main role="main" class="pb-3">
        <div id="msg">

        </div>
        <div class="panel panel-primary">
            <div class="panel-heading text-center">Decrypt</div>
            <div class="panel-body">

                <form method="post" enctype="multipart/form-data">

                    <div class="form-group">
                        <div class="custom-file">
                            <input type="file" asp-for="File" class="custom-file-input" id="inputGroupFile04" required>
                            <label class="custom-file-label" for="inputGroupFile04">Choose file</label>
                        </div>
                        <div class="form-group float-right">
                            <br />
                            <button class="btn btn-primary" asp-page-handler="Decrypt" type="submit">Decrypt</button>
                        </div>
                    </div>



                </form>

            </div>
        </div>
        @if (@ViewData["DecryptionTime"] != null)
        {
            <div class="panel panel-primary">
                <div class="panel-heading text-center">Decryption Time</div>
                <div class="panel-body">
                    <div class="form-group">
                        <input type="text" disabled name="DecryptionTime" value="@ViewData["DecryptionTime"]" />
                    </div>
                </div>
            </div>
        }
        @if (@ViewData["result"] != null)
        {
            <div class="panel panel-primary">
                <div class="panel-heading text-center">Result</div>
                <div class="panel-body">
                    <div class="form-group">
                        <textarea style="height: 200px;" disabled class="form-control">@ViewData["result"]</textarea>
                    </div>
                </div>
            </div>
        }
        <br />
        <br />
        <div class="row">

            <div class="col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-heading text-center">Received Data</div>
                    <div class="panel-body">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Sender</th>
                                    <th scope="col">Receiver</th>
                                    <th scope="col">Date time</th>
                                    <th scope="col">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.UserDatas)
                                {
                                    <tr>
                                        <th scope="row">@item.UserDataId</th>
                                        <td>@item.SenderName</td>
                                        <td>@item.ReceiverName</td>
                                        <td>@item.SendingDatetime.ToString("yy-MMM-dd")</td>
                                        <td><a href="@item.UserDataId?handler=download">Download</a></td>
                                    </tr>
                                }
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>

        </div>
    </main>
</div>
@section Scripts{
    <script>


        function getUserKey() {
            var userId = $('#cmb-user option:selected').val();
            if (userId == '0') {
                showAlert('Select Receiver!.', 'danger');
                return;
            }
            $('#ReceiverName').val($('#cmb-user option:selected').text())
            // ajax call here
            $.ajax({
                contentType: "application/json",
                url: '/Send/' + userId + '?handler=Connect',
                type: 'get'
            }).done(function (response) {
                console.log(response);
                $('#ReceiverKey').val(response);
                showAlert('Connected!.', 'success');
            }).fail(function (xhr, status, error) {
                //Ajax request failed.
                var errorMessage = xhr.status + ': ' + xhr.statusText
                //alert('Error - ' + errorMessage);
                showAlert('Unaable to connect!.', 'danger');
            })

        }

        function showAlert(msg,type) {
            var alert='<div class="alert alert-'+ type +' alert-dismissible fade show" role="alert">'+
                '<strong>'+ msg +'</strong> '+
                '<button type="button" class="close" data-dismiss="alert" aria-label="Close">'+
                    '<span aria-hidden="true">&times;</span>'+
                '</button>'+
            '</div>'
                $('#msg').append(alert);
        }



    </script>

}

QuantumEncryption/Pages/Send.cshtml
@page "{id:int}"
@model QuantumEncryption.Pages.SendModel
@{
    ViewData["Title"] = "Send";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<partial name="_header" model="Model.SessionModel" />
<div class="container">

    <main role="main" class="pb-3">
        <div id="msg">

        </div>
        <div class="panel panel-primary">
            <div class="panel-heading text-center">Encrypt</div>
            <div class="panel-body">

                <form method="post" enctype="multipart/form-data">
                    <div class="form-group ">
                        <label></label>
                        <select class="form-control col-md-12" id="cmb-user" onchange="getUserKey();" name="ReceiverId" required>
                            <option value="0">select User</option>

                            @foreach (var item in Model.LoggedInUsers)
                            {
                                <option value="@item.LoggedInUserId">@item.UserName</option>
                            }
                        </select>
                        @*<button class="btn btn-success" onclick="getUserKey();" type="button">Connect</button>*@
                    </div>
                    <br />
                    <div class="form-group">
                        <div class="custom-file">
                            <input type="hidden" asp-for="ReceiverName" id="ReceiverName" class="custom-file-input">
                            <input type="hidden" asp-for="SenderName" id="SenderName" class="custom-file-input">
                            <input type="hidden" asp-for="ReceiverKey" id="ReceiverKey" class="custom-file-input" required>
                            <input type="file" asp-for="File" class="custom-file-input" id="inputGroupFile04" required>
                            <label class="custom-file-label" for="inputGroupFile04">Choose file</label>
                        </div>

                    </div>

                    <div class="form-group float-right">
                        <br />
                        <button class="btn btn-primary" id="btn-submit" title="Connect user" disabled asp-page-handler="Encrypt" type="submit">Encrypt</button>
                    </div>

                </form>
            </div>
        </div>
        @if (@ViewData["EncryptionTime"] != null)
        {
            <div class="panel panel-primary">
                <div class="panel-heading text-center">Encryption Time</div>
                <div class="panel-body">
                    <div class="form-group">
                        <input type="text" disabled name="EncryptionTime" value="@ViewData["EncryptionTime"]" />
                    </div>
                </div>
            </div>
        }
        @if (@ViewData["result"] != null)
        {
            <div class="panel panel-primary">
                <div class="panel-heading text-center">Result</div>
                <div class="panel-body">
                    <div class="form-group">
                        <textarea style="height: 200px;" disabled class="form-control">@ViewData["result"]</textarea>
                    </div>
                </div>
            </div>
        }

        <br />
        <br />
        <div class="row">
            <div class="col-md-12">


                <div class="panel panel-primary">
                    <div class="panel-heading text-center">Sent Data</div>
                    <div class="panel-body">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Sender</th>
                                    <th scope="col">Receiver</th>
                                    <th scope="col">Date time</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.UserDatas)
                                {
                                    <tr>
                                        <th scope="row">@item.UserDataId</th>
                                        <td>@item.SenderName</td>
                                        <td>@item.ReceiverName</td>
                                        <td>@item.SendingDatetime.ToString("yy-MMM-dd")</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>
@*<div class="panel panel-primary" id="base-div" style="display:none">
    <div class="panel-heading text-center">CIA BASES</div>
    <div class="panel-body">


    </div>
</div>*@

@section Scripts{
    <script>


        function getUserKey() {
            var userId = $('#cmb-user option:selected').val();
            if (userId == '0') {
                showAlert('Select Receiver!.', 'danger');
                return;
            }
            $('#ReceiverName').val($('#cmb-user option:selected').text())
            // ajax call here
            $.ajax({
                contentType: "application/json",
                url: '/Send/' + userId + '?handler=Connect',
                type: 'get'
            }).done(function (response) {
                console.log(response);
                $('#ReceiverKey').val(response);
                $('#btn-submit').removeAttr('disabled');
                showAlert('Connected!.', 'success');
            }).fail(function (xhr, status, error) {
                //Ajax request failed.
                var errorMessage = xhr.status + ': ' + xhr.statusText
                //alert('Error - ' + errorMessage);
                showAlert('Unaable to connect!.', 'danger');
            })

        }

        function showAlert(msg,type) {
            var alert='<div class="alert alert-'+ type +' alert-dismissible fade show" role="alert">'+
                '<strong>'+ msg +'</strong> '+
                '<button type="button" class="close" data-dismiss="alert" aria-label="Close">'+
                    '<span aria-hidden="true">&times;</span>'+
                '</button>'+
            '</div>'
                $('#msg').append(alert);
        }



    </script>

}